In [1]:
from google.colab import files

uploaded = files.upload()

Saving YieldSense_datasets.csv to YieldSense_datasets.csv

In [2]:
import pandas as pd              # Read and manage dataset
import numpy as np               # Math calculations

import matplotlib.pyplot as plt  # Create graphs
import seaborn as sns            # Better graphs

plt.style.use("ggplot")          # Better graph style

In [3]:
# Read CSV dataset

df = pd.read_csv("YieldSense_datasets.csv")

# Show first 5 rows

df.head()

,crop,year,season,state,area,production,fertilizer,pesticide,yield,avg_temp_c,total_rainfall_mm,avg_humidity_percent,N,P,K,pH
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,7024878.38,22882.34,0.796087,22.41,1468.92,70.71,60,18,38,5.8
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,631643.29,2057.47,0.710435,22.41,1468.92,70.71,60,18,38,5.8
2,Castor seed,1997,Kharif,Assam,796.0,22,75755.32,246.76,0.238333,22.41,1468.92,70.71,60,18,38,5.8
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,1870661.52,6093.36,5238.051739,22.41,1468.92,70.71,60,18,38,5.8
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,165500.63,539.09,0.420909,22.41,1468.92,70.71,60,18,38,5.8

In [4]:
# Show number of rows and columns

print("Dataset Shape:", df.shape)

# Show all column names

print("\nColumn Names:")
print(df.columns)

# Show data types of each column

print("\nData Types:")
print(df.dtypes)

Dataset Shape: (19689, 16)

Column Names:
Index(['crop', 'year', 'season', 'state', 'area', 'production', 'fertilizer',
       'pesticide', 'yield', 'avg_temp_c', 'total_rainfall_mm',
       'avg_humidity_percent', 'N', 'P', 'K', 'pH'],
      dtype='object')

Data Types:
crop                     object
year                      int64
season                   object
state                    object
area                    float64
production                int64
fertilizer              float64
pesticide               float64
yield                   float64
avg_temp_c              float64
total_rainfall_mm       float64
avg_humidity_percent    float64
N                         int64
P                         int64
K                         int64
pH                      float64
dtype: object

In [5]:
# Check missing values in each column

df.isnull().sum()

crop                    0
year                    0
season                  0
state                   0
area                    0
production              0
fertilizer              0
pesticide               0
yield                   0
avg_temp_c              0
total_rainfall_mm       0
avg_humidity_percent    0
N                       0
P                       0
K                       0
pH                      0
dtype: int64

In [6]:
# Check duplicate rows

print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [7]:
# Display statistical summary of numerical columns

df.describe()

,year,area,production,fertilizer,pesticide,yield,avg_temp_c,total_rainfall_mm,avg_humidity_percent,N,P,K,pH
count,19689.000000,1.968900e+04,1.968900e+04,1.968900e+04,1.968900e+04,19689.000000,19689.000000,19689.000000,19689.000000,19689.000000,19689.000000,19689.000000,19689.000000
mean,2009.127584,1.799266e+05,1.643594e+07,2.410331e+07,4.884835e+04,79.954009,24.008025,1337.999356,64.676018,76.626847,33.499264,32.234547,6.640292
std,6.498099,7.328287e+05,2.630568e+08,9.494600e+07,2.132874e+05,878.306193,4.408018,637.585197,11.474130,20.060556,11.556686,7.915514,0.690622
min,1997.000000,5.000000e-01,0.000000e+00,5.417000e+01,9.000000e-02,0.000000,6.260000,249.240000,34.470000,50.000000,15.000000,20.000000,5.500000
25%,2004.000000,1.390000e+03,1.393000e+03,1.880146e+05,3.567000e+02,0.600000,22.910000,894.160000,54.620000,65.000000,24.000000,25.000000,6.000000
50%,2010.000000,9.317000e+03,1.380400e+04,1.234957e+06,2.421900e+03,1.030000,25.560000,1172.020000,68.110000,72.000000,38.000000,33.000000,6.600000
75%,2015.000000,7.511200e+04,1.227180e+05,1.000385e+07,2.004170e+04,2.388889,26.810000,1613.400000,73.730000,80.000000,43.000000,38.000000,7.100000
max,2020.000000,5.080810e+07,6.326000e+09,4.835407e+09,1.575051e+07,21105.000000,28.630000,5244.360000,86.060000,150.000000,55.000000,50.000000,8.000000

In [8]:
print("States:", df["state"].nunique())
print("Crops:", df["crop"].nunique())
print("Seasons:", df["season"].nunique())

States: 30
Crops: 55
Seasons: 6

In [10]:
x = df.drop(["production", "yield"], axis = 1)
y = df["yield"]

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x["crop"] = le.fit_transform(x["crop"])
x["season"] = le.fit_transform(x["season"])
x["state"] = le.fit_transform(x["state"])

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(

    x,
    y,
    test_size=0.2,
    random_state=42

)

In [14]:
from sklearn.ensemble import AdaBoostRegressor
adaboost = AdaBoostRegressor(
    random_state=42
)
adaboost.fit(X_train, y_train)
y_pred = adaboost.predict(X_test)

In [15]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

In [16]:
mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R² Score:", r2)

MAE : 22.479356664186977
MSE : 39024.87569705598
RMSE: 197.54714803574356
R² Score: 0.9512943908482034